server:
  port: 8091

spring:
  application:
    name: PRODUTO-CLIENT
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microsservicos_produtos # Nome do banco de dados que você deseja usar no MongoDB
      auto-index-creation: true # Criação automática de índices
      auto-initialize: true # Inicialização automática do banco de dados

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}



